# Generated by Django 3.2.7 on 2021-09-24 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.TextField()),
                ('added_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
