# Generated by Django 3.2.7 on 2021-09-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=models.CharField(max_length=25),
        ),
    ]
