# Generated by Django 3.2.7 on 2021-09-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_tracker', '0002_alter_userlocation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=25)),
                ('location_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='id',
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_tracker.geolocation'),
        ),
    ]
