# Generated by Django 3.2.7 on 2021-09-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_tracker', '0003_auto_20210924_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
